vocab_size: 32768
hidden_size: 640
intermediate_size: 1792
num_attention_heads: 8
num_layers: 12
dropout: 0.0
rms_norm_eps: 1.0e-05
max_position_embeddings: 2048
rotary_pct: 0.25
rope_theta: 10000.0
gradient_checkpointing: true
dtype: float32
